Polygon robustness (#111)
* When polygon union fails, just don't display a region overlay rather than a broken one
* Hotfix: Disable overlay polygon by default for now until it's properly fixes

Also: Don't update regions automatically when changing development server

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -45,7 +45,14 @@ jobs:
         DD_TEST_RUNNER: 1
         DD_ENV: ci
         DD_SERVICE: tripkit-ios
-      run: xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8'
+      run: |
+        xcodebuild test -project TripKit.xcodeproj -scheme "TripKit-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' -resultBundlePath TestResults
+    - uses: kishikawakatsumi/xcresulttool@v1.0.3
+      with:
+        path: TestResults.xcresult
+      if: success() || failure()
+      # ^ This is important because the action will be run
+      # even if the test fails in the previous step.
 
   examples:
     runs-on: macos-11
